"""""""""""""""""""""""""""""""""""""""""""
"
" ███████  ███████  ███████  ███████
" ██    █  █        █           █
" ██████   ██████   ██████      █
" ██    █  █              █     █
" ███████  ███████  ██████      █
"
" 
" Maintainer: Asaf Rafaeli
" 
" Contents:
"   » General
"   » Interface
"   » Navigation
"   » Editing
"   » Status line
"
"""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""""""
" » General
"""""""""""""""""""""""""""""""""""""""""""

" Enable pathogen
call pathogen#infect()

" Enable filetype plugins
filetype plugin indent on

" Auto-read file when changed
set autoread

" File type recognition
augroup vimrc_filetypes
  autocmd!
  autocmd BufNewFile,BufRead *.Dockerfile setf dockerfile
  autocmd BufNewFile,BufRead *.dockerfile setf dockerfile
  autocmd BufNewFile,BufReadPost *.md set filetype=markdown
augroup END

" Update shit 250ms
set updatetime=250

" Turn backup off, since most stuff is in SVN, git et.c anyway...
set nobackup
set nowb
set noswapfile


"""""""""""""""""""""""""""""""""""""""""""
" » Interface
"""""""""""""""""""""""""""""""""""""""""""

" Enable syntax hilighting
syntax enable

" Python syntax
let python_highlight_all = 1

" Jedi python autocompletion
set splitbelow

" Highlight colors in code
augroup vimrc_hlcolor
  autocmd!
  autocmd BufNewFile,BufRead * ColorHighlight
augroup END

" Highlight text during searches
set hlsearch

" Show line numbers
set number
set relativenumber

" Column line
set colorcolumn=120

" Line number and gutter colors
let g:gitgutter_override_sign_column_highlight = 0
" highlight LineNr ctermbg=grey guibg=grey
" highlight SignColumn ctermbg=grey guibg=grey

" Highlight current line
set cursorline

" Tab navigation like Firefox.
"nnoremap <C-S-h> :tabprevious<CR>
"nnoremap <C-S-l>   :tabnext<CR>
"nnoremap <C-t>     :tabnew<CR>
"inoremap <C-S-h> <Esc>:tabprevious<CR>i
"inoremap <C-S-l>   <Esc>:tabnext<CR>i
"inoremap <C-t>     <Esc>:tabnew<CR>
nnoremap <leader>th :tabprevious<CR>
nnoremap <leader>tl   :tabnext<CR>
nnoremap <leader>tt     :tabnew<CR>
inoremap <leader>th <Esc>:tabprevious<CR>i
inoremap <leader>tl   <Esc>:tabnext<CR>i
inoremap <leader>tt     <Esc>:tabnew<CR>

"""""""""""""""""""""""""""""""""""""""""""
" » Navigation
"""""""""""""""""""""""""""""""""""""""""""

" Sane split navigation
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>

" NERDTree
map <C-n> :NERDTreeToggle<CR>

" CtrlP fuzzy file finder
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'


"""""""""""""""""""""""""""""""""""""""""""
" » Editing
"""""""""""""""""""""""""""""""""""""""""""

" Save and quit remappings
map <C-s> :w<CR>
map <C-q> :q<CR>

" Indentation (tab=2 spaces, autoindent)
set et
set tabstop=2
set shiftwidth=2
set ai

" PEP8
set textwidth=119
let $PATH .= ';/home/asaf/.pyenv/shims'

augroup vimrc_flake8
  autocmd!
  autocmd BufWritePost *.py call Flake8()
augroup END


"""""""""""""""""""""""""""""""""""""""""""
" » Status line
"""""""""""""""""""""""""""""""""""""""""""

" Statusline ON
set noruler
set laststatus=2


"""""""""""""""""""""""""""""""""""""""""""
" » Misc
"""""""""""""""""""""""""""""""""""""""""""

" GUI Stuff (Colorscheme)
" colorscheme Kafka
colors angr

" Remove annoying tilde ~ on empty lines
hi NonText guifg=bg

" set guifont=Source\ Code\ Pro\ for\ Powerline\ 12
set guifont=Monaco\ 14
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar

" air-line
let g:airline_powerline_fonts = 1
let g:airline_theme='angr'

