" Enable syntax hilighting
syntax enable

" Highlight text during searches
set hlsearch

" <Ctrl-l> redraws the screen and removes any search hilighting.
nnoremap <silent> <esc> :nohl<CR><esc>

" <Ctrl-n> toggles NERDTree
map <C-n> :NERDTreeToggle<CR>

" Sane split navigation
nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>

" <Ctrl-l> redraws the screen and removes any search hilighting.
" nnoremap <silent> <F5> :source $MYVIMRC<CR>:echo 'Reloaded vimrc'<CR>

" Show line numbers
set number
set relativenumber

" Space indentation
set et
set tabstop=2
set shiftwidth=2

" Auto indentation
set ai

" CtrlP
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

" Force markdown filetype for *.md
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" Enable pathogen
call pathogen#infect()

" Enable coffeescript-vim
filetype plugin indent on

" Statusline fun
set noruler
set laststatus=2
" set statusline=%f\ -\ FileType:\ %y

" GUI Stuff (Colorscheme)
colorscheme Kafka
set guifont=Source\ Code\ Pro\ for\ Powerline\ 12
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar

" air-line
let g:airline_powerline_fonts = 1

let g:Powerline_symbols = 'fancy'

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
" let g:airline_left_sep = '»'
" let g:airline_left_sep = '▶'
" let g:airline_right_sep = '«'
" let g:airline_right_sep = '◀'
" let g:airline_symbols.linenr = '␊'
" let g:airline_symbols.linenr = '␤'
" let g:airline_symbols.linenr = '¶'
" let g:airline_symbols.branch = '⎇'
" let g:airline_symbols.paste = 'ρ'
" let g:airline_symbols.paste = 'Þ'
" let g:airline_symbols.paste = '∥'
" let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
" let g:airline_left_sep = ''
" let g:airline_left_alt_sep = ''
" let g:airline_right_sep = ''
" let g:airline_right_alt_sep = ''
" let g:airline_symbols.branch = ''
" let g:airline_symbols.readonly = ''
" let g:airline_symbols.linenr = ''
